package com.qhzk.pe.entities;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table code_column_config
 */
public class ColumnInfo implements Serializable {
    @ApiModelProperty(value = "ID")
    private Long columnId;

    private String tableName;

    private String columnName;

    private String columnType;

    private String dictName;

    private String extra;

    private Boolean formShow;

    private String formType;

    private String keyType;

    private Boolean listShow;

    private Boolean notNull;

    private String queryType;

    private String remark;

    private String dateAnnotation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table code_column_config
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_column_config.column_id
     *
     * @return the value of code_column_config.column_id
     *
     * @mbg.generated
     */
    public Long getColumnId() {
        return columnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_column_config.column_id
     *
     * @param columnId the value for code_column_config.column_id
     *
     * @mbg.generated
     */
    public void setColumnId(Long columnId) {
        this.columnId = columnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_column_config.table_name
     *
     * @return the value of code_column_config.table_name
     *
     * @mbg.generated
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_column_config.table_name
     *
     * @param tableName the value for code_column_config.table_name
     *
     * @mbg.generated
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_column_config.column_name
     *
     * @return the value of code_column_config.column_name
     *
     * @mbg.generated
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_column_config.column_name
     *
     * @param columnName the value for code_column_config.column_name
     *
     * @mbg.generated
     */
    public void setColumnName(String columnName) {
        this.columnName = columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_column_config.column_type
     *
     * @return the value of code_column_config.column_type
     *
     * @mbg.generated
     */
    public String getColumnType() {
        return columnType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_column_config.column_type
     *
     * @param columnType the value for code_column_config.column_type
     *
     * @mbg.generated
     */
    public void setColumnType(String columnType) {
        this.columnType = columnType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_column_config.dict_name
     *
     * @return the value of code_column_config.dict_name
     *
     * @mbg.generated
     */
    public String getDictName() {
        return dictName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_column_config.dict_name
     *
     * @param dictName the value for code_column_config.dict_name
     *
     * @mbg.generated
     */
    public void setDictName(String dictName) {
        this.dictName = dictName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_column_config.extra
     *
     * @return the value of code_column_config.extra
     *
     * @mbg.generated
     */
    public String getExtra() {
        return extra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_column_config.extra
     *
     * @param extra the value for code_column_config.extra
     *
     * @mbg.generated
     */
    public void setExtra(String extra) {
        this.extra = extra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_column_config.form_show
     *
     * @return the value of code_column_config.form_show
     *
     * @mbg.generated
     */
    public Boolean getFormShow() {
        return formShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_column_config.form_show
     *
     * @param formShow the value for code_column_config.form_show
     *
     * @mbg.generated
     */
    public void setFormShow(Boolean formShow) {
        this.formShow = formShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_column_config.form_type
     *
     * @return the value of code_column_config.form_type
     *
     * @mbg.generated
     */
    public String getFormType() {
        return formType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_column_config.form_type
     *
     * @param formType the value for code_column_config.form_type
     *
     * @mbg.generated
     */
    public void setFormType(String formType) {
        this.formType = formType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_column_config.key_type
     *
     * @return the value of code_column_config.key_type
     *
     * @mbg.generated
     */
    public String getKeyType() {
        return keyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_column_config.key_type
     *
     * @param keyType the value for code_column_config.key_type
     *
     * @mbg.generated
     */
    public void setKeyType(String keyType) {
        this.keyType = keyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_column_config.list_show
     *
     * @return the value of code_column_config.list_show
     *
     * @mbg.generated
     */
    public Boolean getListShow() {
        return listShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_column_config.list_show
     *
     * @param listShow the value for code_column_config.list_show
     *
     * @mbg.generated
     */
    public void setListShow(Boolean listShow) {
        this.listShow = listShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_column_config.not_null
     *
     * @return the value of code_column_config.not_null
     *
     * @mbg.generated
     */
    public Boolean getNotNull() {
        return notNull;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_column_config.not_null
     *
     * @param notNull the value for code_column_config.not_null
     *
     * @mbg.generated
     */
    public void setNotNull(Boolean notNull) {
        this.notNull = notNull;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_column_config.query_type
     *
     * @return the value of code_column_config.query_type
     *
     * @mbg.generated
     */
    public String getQueryType() {
        return queryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_column_config.query_type
     *
     * @param queryType the value for code_column_config.query_type
     *
     * @mbg.generated
     */
    public void setQueryType(String queryType) {
        this.queryType = queryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_column_config.remark
     *
     * @return the value of code_column_config.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_column_config.remark
     *
     * @param remark the value for code_column_config.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_column_config.date_annotation
     *
     * @return the value of code_column_config.date_annotation
     *
     * @mbg.generated
     */
    public String getDateAnnotation() {
        return dateAnnotation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_column_config.date_annotation
     *
     * @param dateAnnotation the value for code_column_config.date_annotation
     *
     * @mbg.generated
     */
    public void setDateAnnotation(String dateAnnotation) {
        this.dateAnnotation = dateAnnotation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_column_config
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", columnId=").append(columnId);
        sb.append(", tableName=").append(tableName);
        sb.append(", columnName=").append(columnName);
        sb.append(", columnType=").append(columnType);
        sb.append(", dictName=").append(dictName);
        sb.append(", extra=").append(extra);
        sb.append(", formShow=").append(formShow);
        sb.append(", formType=").append(formType);
        sb.append(", keyType=").append(keyType);
        sb.append(", listShow=").append(listShow);
        sb.append(", notNull=").append(notNull);
        sb.append(", queryType=").append(queryType);
        sb.append(", remark=").append(remark);
        sb.append(", dateAnnotation=").append(dateAnnotation);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}