package com.qhzk.pe.entities;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   权限-页面元素信息表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_as_permiss_pelement
 */
public class PermissPelement implements Serializable {
    @ApiModelProperty(value = "id")
    private Long id;

    @ApiModelProperty(value = "权限id")
    private Long permissid;

    @ApiModelProperty(value = "页面元素id")
    private Long pelid;

    @ApiModelProperty(value = "排序")
    private String seq;

    @ApiModelProperty(value = "创建人")
    private String creator;

    @ApiModelProperty(value = "创建时间 ")
    private Date createtime;

    @ApiModelProperty(value = "最后一次操作者")
    private String operator;

    @ApiModelProperty(value = " 最后一次 操作时间 ")
    private Date operatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_as_permiss_pelement
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_permiss_pelement.id
     *
     * @return the value of t_as_permiss_pelement.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_permiss_pelement.id
     *
     * @param id the value for t_as_permiss_pelement.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_permiss_pelement.permissid
     *
     * @return the value of t_as_permiss_pelement.permissid
     *
     * @mbg.generated
     */
    public Long getPermissid() {
        return permissid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_permiss_pelement.permissid
     *
     * @param permissid the value for t_as_permiss_pelement.permissid
     *
     * @mbg.generated
     */
    public void setPermissid(Long permissid) {
        this.permissid = permissid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_permiss_pelement.pelid
     *
     * @return the value of t_as_permiss_pelement.pelid
     *
     * @mbg.generated
     */
    public Long getPelid() {
        return pelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_permiss_pelement.pelid
     *
     * @param pelid the value for t_as_permiss_pelement.pelid
     *
     * @mbg.generated
     */
    public void setPelid(Long pelid) {
        this.pelid = pelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_permiss_pelement.seq
     *
     * @return the value of t_as_permiss_pelement.seq
     *
     * @mbg.generated
     */
    public String getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_permiss_pelement.seq
     *
     * @param seq the value for t_as_permiss_pelement.seq
     *
     * @mbg.generated
     */
    public void setSeq(String seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_permiss_pelement.creator
     *
     * @return the value of t_as_permiss_pelement.creator
     *
     * @mbg.generated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_permiss_pelement.creator
     *
     * @param creator the value for t_as_permiss_pelement.creator
     *
     * @mbg.generated
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_permiss_pelement.createtime
     *
     * @return the value of t_as_permiss_pelement.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_permiss_pelement.createtime
     *
     * @param createtime the value for t_as_permiss_pelement.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_permiss_pelement.operator
     *
     * @return the value of t_as_permiss_pelement.operator
     *
     * @mbg.generated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_permiss_pelement.operator
     *
     * @param operator the value for t_as_permiss_pelement.operator
     *
     * @mbg.generated
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_permiss_pelement.operatetime
     *
     * @return the value of t_as_permiss_pelement.operatetime
     *
     * @mbg.generated
     */
    public Date getOperatetime() {
        return operatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_permiss_pelement.operatetime
     *
     * @param operatetime the value for t_as_permiss_pelement.operatetime
     *
     * @mbg.generated
     */
    public void setOperatetime(Date operatetime) {
        this.operatetime = operatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_permiss_pelement
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", permissid=").append(permissid);
        sb.append(", pelid=").append(pelid);
        sb.append(", seq=").append(seq);
        sb.append(", creator=").append(creator);
        sb.append(", createtime=").append(createtime);
        sb.append(", operator=").append(operator);
        sb.append(", operatetime=").append(operatetime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}