package com.qhzk.as.entity;

import com.baomidou.mybatisplus.annotation.TableName;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table code_column_config
 */
@TableName("code_column_config")
public class ColumnInfo implements Serializable {
    @ApiModelProperty(value = "ID")
    private Long columnId;
    @ApiModelProperty(value = "表名")
    private String tableName;
    @ApiModelProperty(value = "字段名")
    private String columnName;
    @ApiModelProperty(value = "字段类型")
    private String columnType;
    @ApiModelProperty(value = "字典")
    private String dictName;
    @ApiModelProperty(value = "")
    private String extra;
    @ApiModelProperty(value = "")
    private Boolean formShow =true;
    @ApiModelProperty(value = "")
    private String formType;
    @ApiModelProperty(value = "")
    private String keyType;
    @ApiModelProperty(value = "")
    private Boolean listShow = true;
    @ApiModelProperty(value = "")
    private String nullable;
    @ApiModelProperty(value = "")
    private Boolean notNull;
    @ApiModelProperty(value = "")
    private String queryType;
    @ApiModelProperty(value = "")
    private String remark;
    @ApiModelProperty(value = "备注")
    private String dateAnnotation;

    public String getNullable() {
        return nullable;
    }

    public void setNullable(String nullable) {
        this.setNotNull("NO".equals(nullable));
        this.nullable = nullable;
    }

    public Long getColumnId() {
        return columnId;
    }

    public void setColumnId(Long columnId) {
        this.columnId = columnId;
    }

    public String getTableName() {
        return tableName;
    }

    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    public String getColumnName() {
        return columnName;
    }

    public void setColumnName(String columnName) {
        this.columnName = columnName;
    }

    public String getColumnType() {
        return columnType;
    }

    public void setColumnType(String columnType) {
        this.columnType = columnType;
    }

    public String getDictName() {
        return dictName;
    }

    public void setDictName(String dictName) {
        this.dictName = dictName;
    }

    public String getExtra() {
        return extra;
    }

    public void setExtra(String extra) {
        if("PRI".equalsIgnoreCase(this.keyType) && "auto_increment".equalsIgnoreCase(extra)){
            this.setNotNull(false);
        }
        this.extra = extra;
    }

    public Boolean getFormShow() {
        return formShow;
    }

    public void setFormShow(Boolean formShow) {
        this.formShow = formShow;
    }

    public String getFormType() {
        return formType;
    }

    public void setFormType(String formType) {
        this.formType = formType;
    }

    public String getKeyType() {
        return keyType;
    }

    public void setKeyType(String keyType) {
        if("PRI".equalsIgnoreCase(keyType) && "auto_increment".equalsIgnoreCase(this.extra)){
            this.setNotNull(false);
        }
        this.keyType = keyType;
    }

    public Boolean getListShow() {
        return listShow;
    }

    public void setListShow(Boolean listShow) {
        this.listShow = listShow;
    }

    public Boolean getNotNull() {
        return notNull;
    }

    public void setNotNull(Boolean notNull) {
        this.notNull = notNull;
    }

    public String getQueryType() {
        return queryType;
    }

    public void setQueryType(String queryType) {
        this.queryType = queryType;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getDateAnnotation() {
        return dateAnnotation;
    }

    public void setDateAnnotation(String dateAnnotation) {
        this.dateAnnotation = dateAnnotation;
    }
}
