package com.qhzk.as.entity;

import com.baomidou.mybatisplus.annotation.TableName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   公司信息表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_as_company
 */
@ApiModel(value = "公司信息表")
@TableName("t_as_company")
public class Company implements Serializable {
    @ApiModelProperty(value = "公司id")
    private Long id;

    @ApiModelProperty(value = "公司名称")
    private String companyname;

    @ApiModelProperty(value = "法定代表人")
    private String legal;

    @ApiModelProperty(value = "注册资本")
    private String capital;

    @ApiModelProperty(value = "经营状态")
    private String ostatus;

    @ApiModelProperty(value = "成立日期")
    private String estabdate;

    @ApiModelProperty(value = "组织机构代码")
    private String orgcode;

    @ApiModelProperty(value = "纳税人识别号")
    private String taxpayerno;

    @ApiModelProperty(value = "统一信用代码")
    private String creditcode;

    @ApiModelProperty(value = "公司类型")
    private String companytype;

    @ApiModelProperty(value = "所属行业")
    private String industry;

    @ApiModelProperty(value = "所属地区")
    private String region;

    @ApiModelProperty(value = "英文名称")
    private String enname;

    @ApiModelProperty(value = "经营方式")
    private String businestype;

    @ApiModelProperty(value = "人员规模")
    private String staffsize;

    @ApiModelProperty(value = "企业地址")
    private String address;

    @ApiModelProperty(value = "经营范围")
    private String businesscope;

    @ApiModelProperty(value = "官网")
    private String website;

    @ApiModelProperty(value = "联系号码")
    private String contactnum;

    @ApiModelProperty(value = "邮箱地址")
    private String email;

    @ApiModelProperty(value = "公司描述")
    private String remark;

    private String seq;

    @ApiModelProperty(value = "1:正常 0:冻结2：删除")
    private String status;

    @ApiModelProperty(value = "创建人")
    private String creator;

    @ApiModelProperty(value = "创建时间")
    private Date createtime;

    private String operator;

    @ApiModelProperty(value = "最后一次创建时间")
    private Date operatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_as_company
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_company.id
     *
     * @return the value of t_as_company.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_company.id
     *
     * @param id the value for t_as_company.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_company.companyname
     *
     * @return the value of t_as_company.companyname
     *
     * @mbg.generated
     */
    public String getCompanyname() {
        return companyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_company.companyname
     *
     * @param companyname the value for t_as_company.companyname
     *
     * @mbg.generated
     */
    public void setCompanyname(String companyname) {
        this.companyname = companyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_company.legal
     *
     * @return the value of t_as_company.legal
     *
     * @mbg.generated
     */
    public String getLegal() {
        return legal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_company.legal
     *
     * @param legal the value for t_as_company.legal
     *
     * @mbg.generated
     */
    public void setLegal(String legal) {
        this.legal = legal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_company.capital
     *
     * @return the value of t_as_company.capital
     *
     * @mbg.generated
     */
    public String getCapital() {
        return capital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_company.capital
     *
     * @param capital the value for t_as_company.capital
     *
     * @mbg.generated
     */
    public void setCapital(String capital) {
        this.capital = capital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_company.ostatus
     *
     * @return the value of t_as_company.ostatus
     *
     * @mbg.generated
     */
    public String getOstatus() {
        return ostatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_company.ostatus
     *
     * @param ostatus the value for t_as_company.ostatus
     *
     * @mbg.generated
     */
    public void setOstatus(String ostatus) {
        this.ostatus = ostatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_company.estabdate
     *
     * @return the value of t_as_company.estabdate
     *
     * @mbg.generated
     */
    public String getEstabdate() {
        return estabdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_company.estabdate
     *
     * @param estabdate the value for t_as_company.estabdate
     *
     * @mbg.generated
     */
    public void setEstabdate(String estabdate) {
        this.estabdate = estabdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_company.orgcode
     *
     * @return the value of t_as_company.orgcode
     *
     * @mbg.generated
     */
    public String getOrgcode() {
        return orgcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_company.orgcode
     *
     * @param orgcode the value for t_as_company.orgcode
     *
     * @mbg.generated
     */
    public void setOrgcode(String orgcode) {
        this.orgcode = orgcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_company.taxpayerno
     *
     * @return the value of t_as_company.taxpayerno
     *
     * @mbg.generated
     */
    public String getTaxpayerno() {
        return taxpayerno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_company.taxpayerno
     *
     * @param taxpayerno the value for t_as_company.taxpayerno
     *
     * @mbg.generated
     */
    public void setTaxpayerno(String taxpayerno) {
        this.taxpayerno = taxpayerno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_company.creditcode
     *
     * @return the value of t_as_company.creditcode
     *
     * @mbg.generated
     */
    public String getCreditcode() {
        return creditcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_company.creditcode
     *
     * @param creditcode the value for t_as_company.creditcode
     *
     * @mbg.generated
     */
    public void setCreditcode(String creditcode) {
        this.creditcode = creditcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_company.companytype
     *
     * @return the value of t_as_company.companytype
     *
     * @mbg.generated
     */
    public String getCompanytype() {
        return companytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_company.companytype
     *
     * @param companytype the value for t_as_company.companytype
     *
     * @mbg.generated
     */
    public void setCompanytype(String companytype) {
        this.companytype = companytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_company.industry
     *
     * @return the value of t_as_company.industry
     *
     * @mbg.generated
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_company.industry
     *
     * @param industry the value for t_as_company.industry
     *
     * @mbg.generated
     */
    public void setIndustry(String industry) {
        this.industry = industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_company.region
     *
     * @return the value of t_as_company.region
     *
     * @mbg.generated
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_company.region
     *
     * @param region the value for t_as_company.region
     *
     * @mbg.generated
     */
    public void setRegion(String region) {
        this.region = region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_company.enname
     *
     * @return the value of t_as_company.enname
     *
     * @mbg.generated
     */
    public String getEnname() {
        return enname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_company.enname
     *
     * @param enname the value for t_as_company.enname
     *
     * @mbg.generated
     */
    public void setEnname(String enname) {
        this.enname = enname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_company.businestype
     *
     * @return the value of t_as_company.businestype
     *
     * @mbg.generated
     */
    public String getBusinestype() {
        return businestype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_company.businestype
     *
     * @param businestype the value for t_as_company.businestype
     *
     * @mbg.generated
     */
    public void setBusinestype(String businestype) {
        this.businestype = businestype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_company.staffsize
     *
     * @return the value of t_as_company.staffsize
     *
     * @mbg.generated
     */
    public String getStaffsize() {
        return staffsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_company.staffsize
     *
     * @param staffsize the value for t_as_company.staffsize
     *
     * @mbg.generated
     */
    public void setStaffsize(String staffsize) {
        this.staffsize = staffsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_company.address
     *
     * @return the value of t_as_company.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_company.address
     *
     * @param address the value for t_as_company.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_company.businesscope
     *
     * @return the value of t_as_company.businesscope
     *
     * @mbg.generated
     */
    public String getBusinesscope() {
        return businesscope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_company.businesscope
     *
     * @param businesscope the value for t_as_company.businesscope
     *
     * @mbg.generated
     */
    public void setBusinesscope(String businesscope) {
        this.businesscope = businesscope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_company.website
     *
     * @return the value of t_as_company.website
     *
     * @mbg.generated
     */
    public String getWebsite() {
        return website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_company.website
     *
     * @param website the value for t_as_company.website
     *
     * @mbg.generated
     */
    public void setWebsite(String website) {
        this.website = website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_company.contactnum
     *
     * @return the value of t_as_company.contactnum
     *
     * @mbg.generated
     */
    public String getContactnum() {
        return contactnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_company.contactnum
     *
     * @param contactnum the value for t_as_company.contactnum
     *
     * @mbg.generated
     */
    public void setContactnum(String contactnum) {
        this.contactnum = contactnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_company.email
     *
     * @return the value of t_as_company.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_company.email
     *
     * @param email the value for t_as_company.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_company.remark
     *
     * @return the value of t_as_company.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_company.remark
     *
     * @param remark the value for t_as_company.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_company.seq
     *
     * @return the value of t_as_company.seq
     *
     * @mbg.generated
     */
    public String getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_company.seq
     *
     * @param seq the value for t_as_company.seq
     *
     * @mbg.generated
     */
    public void setSeq(String seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_company.status
     *
     * @return the value of t_as_company.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_company.status
     *
     * @param status the value for t_as_company.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_company.creator
     *
     * @return the value of t_as_company.creator
     *
     * @mbg.generated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_company.creator
     *
     * @param creator the value for t_as_company.creator
     *
     * @mbg.generated
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_company.createtime
     *
     * @return the value of t_as_company.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_company.createtime
     *
     * @param createtime the value for t_as_company.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_company.operator
     *
     * @return the value of t_as_company.operator
     *
     * @mbg.generated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_company.operator
     *
     * @param operator the value for t_as_company.operator
     *
     * @mbg.generated
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_company.operatetime
     *
     * @return the value of t_as_company.operatetime
     *
     * @mbg.generated
     */
    public Date getOperatetime() {
        return operatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_company.operatetime
     *
     * @param operatetime the value for t_as_company.operatetime
     *
     * @mbg.generated
     */
    public void setOperatetime(Date operatetime) {
        this.operatetime = operatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_company
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", companyname=").append(companyname);
        sb.append(", legal=").append(legal);
        sb.append(", capital=").append(capital);
        sb.append(", ostatus=").append(ostatus);
        sb.append(", estabdate=").append(estabdate);
        sb.append(", orgcode=").append(orgcode);
        sb.append(", taxpayerno=").append(taxpayerno);
        sb.append(", creditcode=").append(creditcode);
        sb.append(", companytype=").append(companytype);
        sb.append(", industry=").append(industry);
        sb.append(", region=").append(region);
        sb.append(", enname=").append(enname);
        sb.append(", businestype=").append(businestype);
        sb.append(", staffsize=").append(staffsize);
        sb.append(", address=").append(address);
        sb.append(", businesscope=").append(businesscope);
        sb.append(", website=").append(website);
        sb.append(", contactnum=").append(contactnum);
        sb.append(", email=").append(email);
        sb.append(", remark=").append(remark);
        sb.append(", seq=").append(seq);
        sb.append(", status=").append(status);
        sb.append(", creator=").append(creator);
        sb.append(", createtime=").append(createtime);
        sb.append(", operator=").append(operator);
        sb.append(", operatetime=").append(operatetime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}
