package com.qhzk.as.entity;

import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

/**
 * Database Table Remarks:
 *   部门信息表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_as_dept
 */
@ApiModel(value = "部门信息表")
@TableName(value = "t_as_dept")
public class Dept implements Serializable {
    @ApiModelProperty(value = "部门id")
    private Long id;

    @ApiModelProperty(value = "部门名称")
    private String name;

    @ApiModelProperty(value = "上级部门id")
    private Long parentid;

    @ApiModelProperty(value = "公司id")
    private Long companyid;

    @ApiModelProperty(value = "部门层级")
    private String level;

    private String seq;

    @ApiModelProperty(value = "1:正常 0:冻结2：删除")
    private String status;

    private String remark;

    @ApiModelProperty(value = "创建人")
    private String creator;

    @ApiModelProperty(value = "创建时间")
    private Date createtime;

    @ApiModelProperty(value = "最后一次操作者")
    private String operator;

    @ApiModelProperty(value = "最后一次创建时间")
    private Date operatetime;

    @ApiModelProperty(value = "部门员工")
    @TableField(exist = false)
    private List<User> users;

    @ApiModelProperty(value = "部门员工")
    @TableField(exist = false)
    private List<Dept> childs;

    public List<Dept> getChilds() {
        return childs;
    }

    public void setChilds(List<Dept> childs) {
        this.childs = childs;
    }

    public List<User> getUsers() {
        return users;
    }

    public void setUsers(List<User> users) {
        this.users = users;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_dept.id
     *
     * @return the value of t_as_dept.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_dept.id
     *
     * @param id the value for t_as_dept.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_dept.name
     *
     * @return the value of t_as_dept.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_dept.name
     *
     * @param name the value for t_as_dept.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_dept.parentid
     *
     * @return the value of t_as_dept.parentid
     *
     * @mbg.generated
     */
    public Long getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_dept.parentid
     *
     * @param parentid the value for t_as_dept.parentid
     *
     * @mbg.generated
     */
    public void setParentid(Long parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_dept.companyid
     *
     * @return the value of t_as_dept.companyid
     *
     * @mbg.generated
     */
    public Long getCompanyid() {
        return companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_dept.companyid
     *
     * @param companyid the value for t_as_dept.companyid
     *
     * @mbg.generated
     */
    public void setCompanyid(Long companyid) {
        this.companyid = companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_dept.level
     *
     * @return the value of t_as_dept.level
     *
     * @mbg.generated
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_dept.level
     *
     * @param level the value for t_as_dept.level
     *
     * @mbg.generated
     */
    public void setLevel(String level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_dept.seq
     *
     * @return the value of t_as_dept.seq
     *
     * @mbg.generated
     */
    public String getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_dept.seq
     *
     * @param seq the value for t_as_dept.seq
     *
     * @mbg.generated
     */
    public void setSeq(String seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_dept.status
     *
     * @return the value of t_as_dept.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_dept.status
     *
     * @param status the value for t_as_dept.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_dept.remark
     *
     * @return the value of t_as_dept.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_dept.remark
     *
     * @param remark the value for t_as_dept.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_dept.creator
     *
     * @return the value of t_as_dept.creator
     *
     * @mbg.generated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_dept.creator
     *
     * @param creator the value for t_as_dept.creator
     *
     * @mbg.generated
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_dept.createtime
     *
     * @return the value of t_as_dept.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_dept.createtime
     *
     * @param createtime the value for t_as_dept.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_dept.operator
     *
     * @return the value of t_as_dept.operator
     *
     * @mbg.generated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_dept.operator
     *
     * @param operator the value for t_as_dept.operator
     *
     * @mbg.generated
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_dept.operatetime
     *
     * @return the value of t_as_dept.operatetime
     *
     * @mbg.generated
     */
    public Date getOperatetime() {
        return operatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_dept.operatetime
     *
     * @param operatetime the value for t_as_dept.operatetime
     *
     * @mbg.generated
     */
    public void setOperatetime(Date operatetime) {
        this.operatetime = operatetime;
    }

}
