package com.qhzk.as.entity;

import com.baomidou.mybatisplus.annotation.TableName;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table code_gen_config
 */
@TableName("code_gen_config")
public class GenConfig implements Serializable {
    @ApiModelProperty(value = "ID")
    private Long configId;

    @ApiModelProperty(value = "表名")
    private String tableName;

    @ApiModelProperty(value = "作者")
    private String author;

    @ApiModelProperty(value = "是否覆盖")
    private Boolean cover;

    @ApiModelProperty(value = "模块名称")
    private String moduleName;

    @ApiModelProperty(value = "至于哪个包下")
    private String pack;

    @ApiModelProperty(value = "前端代码生成的路径")
    private String path;

    @ApiModelProperty(value = "前端Api文件路径")
    private String apiPath;

    @ApiModelProperty(value = "表前缀")
    private String prefix;

    @ApiModelProperty(value = "接口名称")
    private String apiAlias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table code_gen_config
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_gen_config.config_id
     *
     * @return the value of code_gen_config.config_id
     *
     * @mbg.generated
     */
    public Long getConfigId() {
        return configId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_gen_config.config_id
     *
     * @param configId the value for code_gen_config.config_id
     *
     * @mbg.generated
     */
    public void setConfigId(Long configId) {
        this.configId = configId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_gen_config.table_name
     *
     * @return the value of code_gen_config.table_name
     *
     * @mbg.generated
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_gen_config.table_name
     *
     * @param tableName the value for code_gen_config.table_name
     *
     * @mbg.generated
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_gen_config.author
     *
     * @return the value of code_gen_config.author
     *
     * @mbg.generated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_gen_config.author
     *
     * @param author the value for code_gen_config.author
     *
     * @mbg.generated
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_gen_config.cover
     *
     * @return the value of code_gen_config.cover
     *
     * @mbg.generated
     */
    public Boolean getCover() {
        return cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_gen_config.cover
     *
     * @param cover the value for code_gen_config.cover
     *
     * @mbg.generated
     */
    public void setCover(Boolean cover) {
        this.cover = cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_gen_config.module_name
     *
     * @return the value of code_gen_config.module_name
     *
     * @mbg.generated
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_gen_config.module_name
     *
     * @param moduleName the value for code_gen_config.module_name
     *
     * @mbg.generated
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_gen_config.pack
     *
     * @return the value of code_gen_config.pack
     *
     * @mbg.generated
     */
    public String getPack() {
        return pack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_gen_config.pack
     *
     * @param pack the value for code_gen_config.pack
     *
     * @mbg.generated
     */
    public void setPack(String pack) {
        this.pack = pack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_gen_config.path
     *
     * @return the value of code_gen_config.path
     *
     * @mbg.generated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_gen_config.path
     *
     * @param path the value for code_gen_config.path
     *
     * @mbg.generated
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_gen_config.api_path
     *
     * @return the value of code_gen_config.api_path
     *
     * @mbg.generated
     */
    public String getApiPath() {
        return apiPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_gen_config.api_path
     *
     * @param apiPath the value for code_gen_config.api_path
     *
     * @mbg.generated
     */
    public void setApiPath(String apiPath) {
        this.apiPath = apiPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_gen_config.prefix
     *
     * @return the value of code_gen_config.prefix
     *
     * @mbg.generated
     */
    public String getPrefix() {
        return prefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_gen_config.prefix
     *
     * @param prefix the value for code_gen_config.prefix
     *
     * @mbg.generated
     */
    public void setPrefix(String prefix) {
        this.prefix = prefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_gen_config.api_alias
     *
     * @return the value of code_gen_config.api_alias
     *
     * @mbg.generated
     */
    public String getApiAlias() {
        return apiAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_gen_config.api_alias
     *
     * @param apiAlias the value for code_gen_config.api_alias
     *
     * @mbg.generated
     */
    public void setApiAlias(String apiAlias) {
        this.apiAlias = apiAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_gen_config
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", configId=").append(configId);
        sb.append(", tableName=").append(tableName);
        sb.append(", author=").append(author);
        sb.append(", cover=").append(cover);
        sb.append(", moduleName=").append(moduleName);
        sb.append(", pack=").append(pack);
        sb.append(", path=").append(path);
        sb.append(", apiPath=").append(apiPath);
        sb.append(", prefix=").append(prefix);
        sb.append(", apiAlias=").append(apiAlias);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}
