package com.qhzk.as.entity;

import com.baomidou.mybatisplus.annotation.TableName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

/**
 * Database Table Remarks:
 *   权限信息表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_as_permissions
 */
@ApiModel(value = "权限信息表")
@TableName("t_as_permissions")
public class Permissions implements Serializable {
    @ApiModelProperty(value = "权限id")
    private Long id;

    @ApiModelProperty(value = "权限代码")
    private String code;

    @ApiModelProperty(value = "权限名称")
    private String name;

    @ApiModelProperty(value = "1:菜单 2:页面元素 3:文件 4:功能操作")
    private String type;

    @ApiModelProperty(value = "1:正常 0:冻结2：删除")
    private String status;

    @ApiModelProperty(value = "排序")
    private String seq;

    @ApiModelProperty(value = "创建人")
    private String creator;

    @ApiModelProperty(value = "创建时间 ")
    private Date createtime;

    @ApiModelProperty(value = "最后一次操作者")
    private String operator;

    @ApiModelProperty(value = " 最后一次 操作时间 ")
    private Date operatetime;

    @ApiModelProperty(value = "操作信息")
    private List<Operate> operates;

    @ApiModelProperty(value = "页面元素信息")
    private List<Pelement> pelements;

    @ApiModelProperty(value = "文件信息")
    private List<FileInfo> files;

    @ApiModelProperty(value = "菜单信息")
    private List<Menu> menus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_permissions.id
     *
     * @return the value of t_as_permissions.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_permissions.id
     *
     * @param id the value for t_as_permissions.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_permissions.code
     *
     * @return the value of t_as_permissions.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_permissions.code
     *
     * @param code the value for t_as_permissions.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_permissions.name
     *
     * @return the value of t_as_permissions.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_permissions.name
     *
     * @param name the value for t_as_permissions.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_permissions.type
     *
     * @return the value of t_as_permissions.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_permissions.type
     *
     * @param type the value for t_as_permissions.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_permissions.status
     *
     * @return the value of t_as_permissions.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_permissions.status
     *
     * @param status the value for t_as_permissions.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_permissions.seq
     *
     * @return the value of t_as_permissions.seq
     *
     * @mbg.generated
     */
    public String getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_permissions.seq
     *
     * @param seq the value for t_as_permissions.seq
     *
     * @mbg.generated
     */
    public void setSeq(String seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_permissions.creator
     *
     * @return the value of t_as_permissions.creator
     *
     * @mbg.generated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_permissions.creator
     *
     * @param creator the value for t_as_permissions.creator
     *
     * @mbg.generated
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_permissions.createtime
     *
     * @return the value of t_as_permissions.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_permissions.createtime
     *
     * @param createtime the value for t_as_permissions.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_permissions.operator
     *
     * @return the value of t_as_permissions.operator
     *
     * @mbg.generated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_permissions.operator
     *
     * @param operator the value for t_as_permissions.operator
     *
     * @mbg.generated
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_as_permissions.operatetime
     *
     * @return the value of t_as_permissions.operatetime
     *
     * @mbg.generated
     */
    public Date getOperatetime() {
        return operatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_as_permissions.operatetime
     *
     * @param operatetime the value for t_as_permissions.operatetime
     *
     * @mbg.generated
     */
    public void setOperatetime(Date operatetime) {
        this.operatetime = operatetime;
    }

    public List<Operate> getOperates() {
        return operates;
    }

    public void setOperates(List<Operate> operates) {
        this.operates = operates;
    }

    public List<Pelement> getPelements() {
        return pelements;
    }

    public void setPelements(List<Pelement> pelements) {
        this.pelements = pelements;
    }

    public List<FileInfo> getFiles() {
        return files;
    }

    public void setFiles(List<FileInfo> files) {
        this.files = files;
    }

    public List<Menu> getMenus() {
        return menus;
    }

    public void setMenus(List<Menu> menus) {
        this.menus = menus;
    }
}
