package com.qhzk.pe.mapper;

import com.qhzk.pe.entities.CompanyUser;
import com.qhzk.pe.entities.CompanyUserCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CompanyUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_company_user
     *
     * @mbg.generated
     */
    long countByExample(CompanyUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_company_user
     *
     * @mbg.generated
     */
    int deleteByExample(CompanyUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_company_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_company_user
     *
     * @mbg.generated
     */
    int insert(CompanyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_company_user
     *
     * @mbg.generated
     */
    int insertSelective(CompanyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_company_user
     *
     * @mbg.generated
     */
    List<CompanyUser> selectByExample(CompanyUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_company_user
     *
     * @mbg.generated
     */
    CompanyUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_company_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CompanyUser record, @Param("example") CompanyUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_company_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CompanyUser record, @Param("example") CompanyUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_company_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CompanyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_company_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CompanyUser record);
}