package com.qhzk.pe.mapper;

import com.qhzk.pe.entities.DeptUser;
import com.qhzk.pe.entities.DeptUserCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeptUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_dept_user
     *
     * @mbg.generated
     */
    long countByExample(DeptUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_dept_user
     *
     * @mbg.generated
     */
    int deleteByExample(DeptUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_dept_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_dept_user
     *
     * @mbg.generated
     */
    int insert(DeptUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_dept_user
     *
     * @mbg.generated
     */
    int insertSelective(DeptUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_dept_user
     *
     * @mbg.generated
     */
    List<DeptUser> selectByExample(DeptUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_dept_user
     *
     * @mbg.generated
     */
    DeptUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_dept_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DeptUser record, @Param("example") DeptUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_dept_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DeptUser record, @Param("example") DeptUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_dept_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DeptUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_dept_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DeptUser record);
}