package com.qhzk.pe.mapper;

import com.qhzk.pe.entities.File;
import com.qhzk.pe.entities.FileCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_file
     *
     * @mbg.generated
     */
    long countByExample(FileCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_file
     *
     * @mbg.generated
     */
    int deleteByExample(FileCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_file
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_file
     *
     * @mbg.generated
     */
    int insert(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_file
     *
     * @mbg.generated
     */
    int insertSelective(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_file
     *
     * @mbg.generated
     */
    List<File> selectByExample(FileCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_file
     *
     * @mbg.generated
     */
    File selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_file
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") File record, @Param("example") FileCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_file
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") File record, @Param("example") FileCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(File record);
}