package com.qhzk.pe.mapper;

import com.qhzk.pe.entities.GenConfig;
import com.qhzk.pe.entities.GenConfigCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GenConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_gen_config
     *
     * @mbg.generated
     */
    long countByExample(GenConfigCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_gen_config
     *
     * @mbg.generated
     */
    int deleteByExample(GenConfigCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_gen_config
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long configId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_gen_config
     *
     * @mbg.generated
     */
    int insert(GenConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_gen_config
     *
     * @mbg.generated
     */
    int insertSelective(GenConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_gen_config
     *
     * @mbg.generated
     */
    List<GenConfig> selectByExample(GenConfigCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_gen_config
     *
     * @mbg.generated
     */
    GenConfig selectByPrimaryKey(Long configId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_gen_config
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GenConfig record, @Param("example") GenConfigCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_gen_config
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GenConfig record, @Param("example") GenConfigCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_gen_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GenConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_gen_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GenConfig record);
}