package com.qhzk.pe.mapper;

import com.qhzk.pe.entities.Pelement;
import com.qhzk.pe.entities.PelementCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PelementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_pelement
     *
     * @mbg.generated
     */
    long countByExample(PelementCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_pelement
     *
     * @mbg.generated
     */
    int deleteByExample(PelementCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_pelement
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_pelement
     *
     * @mbg.generated
     */
    int insert(Pelement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_pelement
     *
     * @mbg.generated
     */
    int insertSelective(Pelement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_pelement
     *
     * @mbg.generated
     */
    List<Pelement> selectByExample(PelementCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_pelement
     *
     * @mbg.generated
     */
    Pelement selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_pelement
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Pelement record, @Param("example") PelementCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_pelement
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Pelement record, @Param("example") PelementCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_pelement
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Pelement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_pelement
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Pelement record);
}