package com.qhzk.pe.mapper;

import com.qhzk.pe.entities.PermissPelement;
import com.qhzk.pe.entities.PermissPelementCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PermissPelementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_permiss_pelement
     *
     * @mbg.generated
     */
    long countByExample(PermissPelementCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_permiss_pelement
     *
     * @mbg.generated
     */
    int deleteByExample(PermissPelementCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_permiss_pelement
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_permiss_pelement
     *
     * @mbg.generated
     */
    int insert(PermissPelement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_permiss_pelement
     *
     * @mbg.generated
     */
    int insertSelective(PermissPelement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_permiss_pelement
     *
     * @mbg.generated
     */
    List<PermissPelement> selectByExample(PermissPelementCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_permiss_pelement
     *
     * @mbg.generated
     */
    PermissPelement selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_permiss_pelement
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PermissPelement record, @Param("example") PermissPelementCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_permiss_pelement
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PermissPelement record, @Param("example") PermissPelementCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_permiss_pelement
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PermissPelement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_permiss_pelement
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PermissPelement record);
}