package com.qhzk.pe.mapper;

import com.qhzk.pe.entities.PermissOperate;
import com.qhzk.pe.entities.PermissOperateCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PermissOperateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_permiss_operate
     *
     * @mbg.generated
     */
    long countByExample(PermissOperateCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_permiss_operate
     *
     * @mbg.generated
     */
    int deleteByExample(PermissOperateCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_permiss_operate
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_permiss_operate
     *
     * @mbg.generated
     */
    int insert(PermissOperate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_permiss_operate
     *
     * @mbg.generated
     */
    int insertSelective(PermissOperate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_permiss_operate
     *
     * @mbg.generated
     */
    List<PermissOperate> selectByExample(PermissOperateCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_permiss_operate
     *
     * @mbg.generated
     */
    PermissOperate selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_permiss_operate
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PermissOperate record, @Param("example") PermissOperateCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_permiss_operate
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PermissOperate record, @Param("example") PermissOperateCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_permiss_operate
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PermissOperate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_permiss_operate
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PermissOperate record);
}