package com.qhzk.pe.mapper;

import com.qhzk.pe.entities.RoleUser;
import com.qhzk.pe.entities.RoleUserCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_role_user
     *
     * @mbg.generated
     */
    long countByExample(RoleUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_role_user
     *
     * @mbg.generated
     */
    int deleteByExample(RoleUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_role_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_role_user
     *
     * @mbg.generated
     */
    int insert(RoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_role_user
     *
     * @mbg.generated
     */
    int insertSelective(RoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_role_user
     *
     * @mbg.generated
     */
    List<RoleUser> selectByExample(RoleUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_role_user
     *
     * @mbg.generated
     */
    RoleUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_role_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RoleUser record, @Param("example") RoleUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_role_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RoleUser record, @Param("example") RoleUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_role_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_role_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RoleUser record);
}