package com.qhzk.pe.mapper;

import com.qhzk.pe.entities.RolePermissions;
import com.qhzk.pe.entities.RolePermissionsCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RolePermissionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_role_permissions
     *
     * @mbg.generated
     */
    long countByExample(RolePermissionsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_role_permissions
     *
     * @mbg.generated
     */
    int deleteByExample(RolePermissionsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_role_permissions
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_role_permissions
     *
     * @mbg.generated
     */
    int insert(RolePermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_role_permissions
     *
     * @mbg.generated
     */
    int insertSelective(RolePermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_role_permissions
     *
     * @mbg.generated
     */
    List<RolePermissions> selectByExample(RolePermissionsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_role_permissions
     *
     * @mbg.generated
     */
    RolePermissions selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_role_permissions
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RolePermissions record, @Param("example") RolePermissionsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_role_permissions
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RolePermissions record, @Param("example") RolePermissionsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_role_permissions
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RolePermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_role_permissions
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RolePermissions record);
}