package com.qhzk.pe.mapper;

import com.qhzk.pe.entities.Ugroup;
import com.qhzk.pe.entities.UgroupCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UgroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_ugroup
     *
     * @mbg.generated
     */
    long countByExample(UgroupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_ugroup
     *
     * @mbg.generated
     */
    int deleteByExample(UgroupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_ugroup
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_ugroup
     *
     * @mbg.generated
     */
    int insert(Ugroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_ugroup
     *
     * @mbg.generated
     */
    int insertSelective(Ugroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_ugroup
     *
     * @mbg.generated
     */
    List<Ugroup> selectByExample(UgroupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_ugroup
     *
     * @mbg.generated
     */
    Ugroup selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_ugroup
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Ugroup record, @Param("example") UgroupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_ugroup
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Ugroup record, @Param("example") UgroupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_ugroup
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Ugroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_ugroup
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Ugroup record);
}