package com.qhzk.pe.mapper;

import com.qhzk.pe.entities.UgroupRole;
import com.qhzk.pe.entities.UgroupRoleCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UgroupRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_ugroup_role
     *
     * @mbg.generated
     */
    long countByExample(UgroupRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_ugroup_role
     *
     * @mbg.generated
     */
    int deleteByExample(UgroupRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_ugroup_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_ugroup_role
     *
     * @mbg.generated
     */
    int insert(UgroupRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_ugroup_role
     *
     * @mbg.generated
     */
    int insertSelective(UgroupRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_ugroup_role
     *
     * @mbg.generated
     */
    List<UgroupRole> selectByExample(UgroupRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_ugroup_role
     *
     * @mbg.generated
     */
    UgroupRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_ugroup_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UgroupRole record, @Param("example") UgroupRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_ugroup_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UgroupRole record, @Param("example") UgroupRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_ugroup_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UgroupRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_as_ugroup_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UgroupRole record);
}