server:
  port: 5001

spring:
  application:
    name:  configuration #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
  profiles:
    active: native

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1026/eureka
