package com.qhzk.autogen.freemark.modle;

/**
 * Database Table Remarks:
 *   评价专家表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_pe_task_expert
 */

public class TaskExpert {

    private Long taskid;

    private Long expertid;

    private Long userid;

    private String usertype;

    private String username;

    private String fullname;

    private String telephone;

    private String expertgroup;
}
