package com.qhzk.autogen.freemark.asplusm;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   公司信息表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_as_company
 */
@ApiModel(value = "公司信息表")
public class Company  {
    @ApiModelProperty(value = "公司id")
    private Long id;

    @ApiModelProperty(value = "公司名称")
    private String companyname;

    @ApiModelProperty(value = "法定代表人")
    private String legal;

    @ApiModelProperty(value = "注册资本")
    private String capital;

    @ApiModelProperty(value = "经营状态")
    private String ostatus;

    @ApiModelProperty(value = "成立日期")
    private String estabdate;

    @ApiModelProperty(value = "组织机构代码")
    private String orgcode;

    @ApiModelProperty(value = "纳税人识别号")
    private String taxpayerno;

    @ApiModelProperty(value = "统一信用代码")
    private String creditcode;

    @ApiModelProperty(value = "公司类型")
    private String companytype;

    @ApiModelProperty(value = "所属行业")
    private String industry;

    @ApiModelProperty(value = "所属地区")
    private String region;

    @ApiModelProperty(value = "英文名称")
    private String enname;

    @ApiModelProperty(value = "经营方式")
    private String businestype;

    @ApiModelProperty(value = "人员规模")
    private String staffsize;

    @ApiModelProperty(value = "企业地址")
    private String address;

    @ApiModelProperty(value = "经营范围")
    private String businesscope;

    @ApiModelProperty(value = "官网")
    private String website;

    @ApiModelProperty(value = "联系号码")
    private String contactnum;

    @ApiModelProperty(value = "邮箱地址")
    private String email;

    @ApiModelProperty(value = "公司描述")
    private String remark;

    private String seq;

    @ApiModelProperty(value = "1:正常 0:冻结2：删除")
    private String status;

    @ApiModelProperty(value = "创建人")
    private String creator;

    @ApiModelProperty(value = "创建时间")
    private Date createtime;

    private String operator;

    @ApiModelProperty(value = "最后一次创建时间")
    private Date operatetime;
}
