package com.qhzk.autogen.freemark.asplusm;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Date;

/**
 * Database Table Remarks:
 *   部门-用户表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_as_dept_user
 */
@ApiModel(value = "部门-用户表")
public class DeptUser {
    @ApiModelProperty(value = "部门id")
    private Long id;

    @ApiModelProperty(value = "部门名称")
    private Long userid;

    @ApiModelProperty(value = "上级部门id")
    private Long deptid;

    private String seq;

    @ApiModelProperty(value = "创建人")
    private String creator;

    @ApiModelProperty(value = "创建时间")
    private Date createtime;

    private String operator;

    @ApiModelProperty(value = "最后一次创建时间")
    private Date operatetime;
}
