server:
  port: 2001
spring:
  application:
    name: gatewayserver
  #############################新增网关配置###########################
  cloud:
    instance:
      hostname: gateway-service
    gateway:
      routes:
      - id: pre_api #路由的ID，没有固定规则但要求唯一，建议配合服务名
        uri: lb://pre-api-server  #匹配后提供服务的路由地址
        predicates:
        - Path=/api/**         # 断言，路径相匹配的进行路由
      - id: provider_pe #路由的ID，没有固定规则但要求唯一，建议配合服务名
        uri: lb://product-evaluation-server #匹配后提供服务的路由地址
        predicates:
        - Path=/pe/**         # 断言，路径相匹配的进行路由
      - id: auth_as #路由的ID，没有固定规则但要求唯一，建议配合服务名
        uri: lb://authenticationserver #匹配后提供服务的路由地址
        predicates:
        - Path=/as/**         # 断言，路径相匹配的进行路由
eureka:
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://127.0.0.1:1026/eureka
